---
settings:
  name: ONTAP Family
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP product documentation
      url: /index.html
product-family:
  search: "clouddocs-ontap_main-prod,clouddocs-ontap-cli-9111_main-prod,,clouddocs-ontap-automation_main-prod,clouddocs-ontap-metrocluster_main-prod,clouddocs-ontap-ems-9111_main-prod"
  sidebarlinks: 
    - title: All
      tags: all,tag_data_management,tag_automation,tag_systems,tag_data_protection,tag_data_migration
      class: active
    - title: Automation
      tags: tag_automation
    - title: Data management 
      tags: tag_data_management
    - title: Data migration 
      tags: tag_data_migration
    - title: Data protection 
      tags: tag_data_protection
    - title: Systems
      tags: tag_systems

  tiles: 
    - title: "ONTAP" 
      icon: ./media/icon-onprem.png
      url: https://docs.netapp.com/us-en/ontap/index.html
      summary: "Deploy and manage ONTAP 9 data management software in your data center using the ONTAP CLI and the latest versions of ONTAP System Manager (ONTAP 9.7 and later)."
      tags: all, tag_data_management, tag_data_protection
    - title: "ONTAP Automation"
      icon: ./media/icon-api.png
      url: https://docs.netapp.com/us-en/ontap-automation/index.html 
      summary: "Automate the deployment and administration of your ONTAP storage systems using the ONTAP REST API and supporting technologies."
      tags: all, tag_automation, tag_data_management
    - title: "ONTAP commands"
      icon: ./media/cli.png
      url: https://docs.netapp.com/us-en/ontap-cli-9111/
      summary: "Learn about the commands available to you in the ONTAP CLI."
      tags: all, tag_data_management
    - title: "ONTAP MetroCluster"
      icon:  ./media/metrocluster.png
      url: https://docs.netapp.com/us-en/ontap-metrocluster/
      summary: "Protect your storage using array-based clustering with synchronous replication to deliver continuous availability."
      tags: all, tag_data_protection
    - title: "AFF and FAS documentation"
      icon: ./media/groups_line.png
      url: https://docs.netapp.com/us-en/ontap-systems-family/
      summary: "Use the AFF and FAS documentation page to find information on how to install, maintain and upgrade your AFF and FAS systems and cluster and storage switches."
      tags: all, tag_systems
    - title: "Cloud Volumes ONTAP"
      icon: ./media/icon-cvo.png
      url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html
      summary: "Deploy a virtual instance of ONTAP to make cloud storage more affordable, intelligent, compliant, and secure."
      tags: all, tag_data_management, tag_data_protection
    - title: ONTAP EMS Reference
      icon: ./media/cli.png
      url: https://docs.netapp.com/us-en/ontap-ems-9111/
      summary: "Learn about the Event Messaging System (EMS) events in ONTAP."
      tags: all, tag_data_management
    - title: "ONTAP SAN Host Configuration"
      icon: ./media/server.png
      url: https://docs.netapp.com/us-en/ontap-sanhost/
      summary: "Configure ONTAP SAN hosts for the NVMe, iSCSI, and FC protocols."
      tags: all, tag_data_management
    - title: "ONTAP System Manager Classic"
      icon: ./media/config_line.png
      url: https://docs.netapp.com/us-en/ontap-sm-classic/index.html
      summary: "ONTAP 9.7 and earlier uses a different layout for the ONTAP System Manager interface."
      tags: all, tag_data_management
    - title: "ONTAP 7-Mode Transition"
      icon: ./media/transition-tools.png
      url: https://docs.netapp.com/us-en/ontap-7mode-transition/
      summary: "Transition data from legacy 7-mode to modern clustered storage platforms."
      tags: all, tag_data_migration
    - title: ONTAP Foreign LUN Import 
      icon: ./media/transition-tools.png
      url: https://docs.netapp.com/us-en/ontap-fli/
      summary: "Migrate LUNs from third-party arrays and 7-mode systems to modern NetApp storage."
      tags: all, tag_data_migration
    - title: "ONTAP Select"
      icon: ./media/server.png
      url: https://docs.netapp.com/us-en/ontap-select/
      summary: "Deploy ONTAP as a software-defined storage appliance on a variety of commodity hardware servers running the VMware ESXi hypervisor."
      tags: all, tag_data_management, tag_data_protection
    - title: "ONTAP FlexArray"
      icon: ./media/cli.png
      url: https://docs.netapp.com/us-en/ontap-flexarray/
      summary: "Use array LUNs to present E-series and third-party arrays as storage served by ONTAP."
      tags: all, tag_data_management





