---
settings:
  name: ONTAP
  search: "ontap,ontap-cli,ontap-automation,ontap-metrocluster,ontap-systems-switches,ontap-technical-reports,ontap-sanhost"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP product documentation
      url: /index.html
product-family:
  sidebarlinks: 
    - title: All
      tags: all
      class: active
    - title: Automation
      tags: automation
    - title: Data management 
      tags: management
    - title: Data migration 
      tags: migration
    - title: Data protection 
      tags: protection
    - title: Hardware systems
      tags: hardware

  tiles: 
    - title: "ONTAP 9 for AFF, ASA, and FAS systems" 
      icon: ./media/icon-onprem.png
      url: https://docs.netapp.com/us-en/ontap/index.html
      summary: "Manage All-Flash FAS systems, All-Flash SAN Array systems, and FAS hybrid-flash arrays using ONTAP 9 data management software."
      tags: all, management, protection
    - title: "ONTAP 9 for ASA r2 systems" 
      icon: ./media/icon-onprem.png
      url: https://docs.netapp.com/us-en/ontap/index.html
      summary: "Manage All-Flash SAN Array r2 systems using ONTAP 9 data management software."
      tags: all, management, protection
    - title: "AFF, ASA, and FAS systems"
      icon: ./media/groups_line.png
      url: https://docs.netapp.com/us-en/ontap-systems-family/
      summary: "Learn how to install, maintain, and upgrade All-Flash FAS systems, All-Flash SAN Array systems, and FAS hybrid-flash arrays, as well as cluster and storage switches."
      tags: all, hardware
    - title: "All-Flash SAN Array r2 systems"
      icon: ./media/groups_line.png
      url: https://docs.netapp.com/us-en/ontap-systems-family/
      summary: "Learn how to install and maintain your All-Flash SAN Array r2 systems."
      tags: all, hardware
    - title: "Cloud Volumes ONTAP"
      icon: ./media/icon-cvo.png
      url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html
      summary: "Deploy a virtual instance of ONTAP to make cloud storage more affordable, intelligent, compliant, and secure."
      tags: all, management, protection
    - title: "ONTAP Select"
      icon: ./media/server.png
      url: https://docs.netapp.com/us-en/ontap-select/
      summary: "Deploy ONTAP as a software-defined storage appliance on a variety of commodity hardware servers running the VMware ESXi hypervisor."
      tags: all, management, protection
    - title: "ONTAP MetroCluster"
      icon:  ./media/metrocluster.png
      url: https://docs.netapp.com/us-en/ontap-metrocluster/
      summary: "Protect your storage using array-based clustering with synchronous replication to deliver continuous availability."
      tags: all, protection
    - title: "ONTAP SAN host configuration"
      icon: ./media/server.png
      url: https://docs.netapp.com/us-en/ontap-sanhost/
      summary: "Configure ONTAP SAN hosts for the NVMe, iSCSI, and FC protocols."
      tags: all, management
    - title: "ONTAP technical reports" 
      icon: ./media/icon-onprem.png
      url: https://docs.netapp.com/us-en/ontap-technical-reports/index.html
      summary: "Learn more about ONTAP architecture and how to optimize ONTAP for specific workloads and environments."
      tags: all, management, protection
    - title: "ONTAP commands"
      icon: ./media/cli.png
      url: https://docs.netapp.com/us-en/ontap-cli/
      summary: "Learn about the commands available to you in the ONTAP CLI."
      tags: all, management
    - title: "ONTAP automation"
      icon: ./media/icon-api.png
      url: https://docs.netapp.com/us-en/ontap-automation/index.html 
      summary: "Automate the deployment and administration of your ONTAP storage systems using the ONTAP REST API and supporting technologies."
      tags: all, automation, management
    - title: ONTAP EMS reference
      icon: ./media/cli.png
      url: https://docs.netapp.com/us-en/ontap-ems-9141/
      summary: "Learn about the Event Messaging System (EMS) events in ONTAP."
      tags: all, management
    - title: "ONTAP 7-Mode Transition"
      icon: ./media/transition-tools.png
      url: https://docs.netapp.com/us-en/ontap-7mode-transition/
      summary: "Transition data from legacy 7-mode to modern clustered storage platforms."
      tags: all, migration
    - title: ONTAP Foreign LUN Import 
      icon: ./media/transition-tools.png
      url: https://docs.netapp.com/us-en/ontap-fli/
      summary: "Migrate LUNs from third-party arrays and 7-mode systems to modern NetApp storage."
      tags: all, migration







