---
settings:
  name: ONTAP
  search: "ontap,ontap-cli,ontap-automation,ontap-metrocluster,ontap-systems-switches,ontap-technical-reports,ontap-sanhost"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP product documentation
      url: /index.html
product-family:
  sidebarlinks: 
    - title: All
      tags: all,tag_data_management,tag_automation,tag_systems,tag_data_protection,tag_data_migration
      class: active
    - title: Cloud
      tags: cloud
    - title: Data management software
      tags: data
    - title: NetApp hardware systems
      tags: hardware
    - title: Software-defined storage
      tags: sds

  tiles: 
    - title: "AFF, ASA, and FAS systems"
      icon: ./media/groups_line.png
      url: https://docs.netapp.com/us-en/ontap-systems-family/
      summary: "Learn how to install, maintain and upgrade your AFF, FAS, and All-Flash SAN Array systems, as well as cluster and storage switches."
      tags: all, hardware
    - title: "ASA r2 systems"
      icon: ./media/groups_line.png
      url: https://docs.netapp.com/us-en/ontap-systems-family/
      summary: "Learn how to install and maintain your All-Flash SAN Array r2 systems."
      tags: all, hardware
    - title: "ONTAP 9 for AFF, FAS, and ASA" 
      icon: ./media/icon-onprem.png
      url: https://docs.netapp.com/us-en/ontap/index.html
      summary: "Manage data on AFF, FAS, and ASA systems using ONTAP 9 data management software."
      tags: all, data
    - title: "ONTAP 9 for ASA r2" 
      icon: ./media/icon-onprem.png
      url: https://docs.netapp.com/us-en/ontap/index.html
      summary: "Manage data on ASA r2 systems using ONTAP 9 data management software."
      tags: all, data
    - title: "Amazon FSx for NetApp ONTAP"
      icon: ./media/icon-cvo.png
      url: https://docs.netapp.com/us-en/ontap-flexarray/
      summary: "Support the most demanding workloads with this fully managed, multiprotocol native file service from AWS."
      tags: all, cloud
    - title: "Azure NetApp Files"
      icon: ./media/icon-cvo.png
      url: https://docs.netapp.com/us-en/ontap-flexarray/
      summary: "Get high-performance file storage for enterprise applications in a native Microsoft Azure file service."
      tags: all, cloud
    - title: "Google Cloud NetApp Volumes"
      icon: ./media/icon-cvo.png
      url: https://docs.netapp.com/us-en/ontap-flexarray/
      summary: "Migrate and manage data and workloads with a fully managed Google Cloud file service."
      tags: all, cloud
    - title: "Cloud Volumes ONTAP"
      icon: ./media/icon-cvo.png
      url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html
      summary: "Deploy a virtual instance of ONTAP to make cloud storage more affordable, intelligent, compliant, and secure."
      tags: all, cloud
    - title: "ONTAP Select"
      icon: ./media/server.png
      url: https://docs.netapp.com/us-en/ontap-select/
      summary: "Deploy ONTAP as a software-defined storage appliance on a variety of commodity hardware servers running the VMware ESXi hypervisor."
      tags: all, sds